### PR TITLE
Fixes #1 with Test

### LINKED ISSUE #1: Should Recursively Apply Roles to Includes
In the following example, values.company.price should return a truthy value but it does not. I have a pull request enroute.

``` javascript
var Company = sequelize.define('company', {
  price: {
    type: Sequelize.FLOAT,
    roles: {
      admin: true
    }
  },
  name: Sequelize.STRING
});

var user = User.build({
  id: 12,
  companyId: 14,
  email: Math.random().toString(),
  password: Math.random().toString(),
  company: {
    id: 14,
    price: Math.random(),
    name: Math.random().toString()
  }
}, {
  role: { system: true }, // I'm not sure what this does
  include: [Company]
});

var values = user.get({role: 'admin'});

expect(values.company.price).to.be.ok();
```

### PR DESCRIPTION
**Pull request by lauzierj**

### CODE REVIEW

**Comment by mickhansen** [comment]
I'm sort of surprised this wouldn't be passing before since the test above passes.

**Comment by lauzierj** [comment]
Internally Sequelize doesn’t pass the options with the role through to the get call for the included instance’s attributes.
- Jacob

**Comment by lauzierj** [comment]
So any attributes on an included instance that has a role specified will return nothing — regardless of the specified role.
- Jacob

**Comment by mickhansen** [comment]
Ah right, and `expect(values.company.price).not.to.be.ok();` still passes because default is no role (so only matches attributes without roles).

**Comment by mickhansen** [comment]
Released as `0.0.4`

**Pull request merged**
